{
 "title": "SwitchBot Meter",
 "tags": [ "switchbot" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature (C) - Indoor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"switchbot\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"switchbot_meter\")\n  |> filter(fn: (r) => r._field == \"tempc\")\n  |> filter(fn: (r) => r.mac != \"C7:8D:2F:CB:6B:1A\")\n  |> group(columns: [\"name\",\"mac\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Temperature (C) - Outside",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"switchbot\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"switchbot_meter\")\n  |> filter(fn: (r) => r._field == \"tempc\")\n  |> filter(fn: (r) => r.mac == \"C7:8D:2F:CB:6B:1A\")\n  |> group(columns: [\"name\",\"mac\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Humidity (%) - Indoor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"switchbot\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"switchbot_meter\")\n  |> filter(fn: (r) => r._field == \"hum\")\n  |> filter(fn: (r) => r.mac != \"C7:8D:2F:CB:6B:1A\")\n  |> group(columns: [\"name\",\"mac\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Humidity (%) - Outside",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"switchbot\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"switchbot_meter\")\n  |> filter(fn: (r) => r._field == \"hum\")\n  |> filter(fn: (r) => r.mac == \"C7:8D:2F:CB:6B:1A\")\n  |> group(columns: [\"name\",\"mac\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}